CREATE DATABASE test;


CREATE TABLE company(id SERIAL PRIMARY KEY,
                                       company_name VARCHAR(255),
                                                    company_name_katakana VARCHAR(255),
                                                                          address VARCHAR(255),
                                                                                  postal_code VARCHAR(255),
                                                                                              phone_number VARCHAR(255),
                                                                                                           email VARCHAR(255),
                                                                                                                 website VARCHAR(255),
                                                                                                                         date_of_establishment DATE, remark VARCHAR(255),
                                                                                                                                                            profile_image VARCHAR(255),
                                                                                                                                                                          UNIQUE(email));


INSERT into company(company_name, company_name_katakana, address, postal_code, phone_number, email, website, date_of_establishment, remark, profile_image)
VALUES ('company_101',
        'カイシャ',
        'address',
        '000-0000',
        '090102030405',
        'company_101@gmail.com',
        'www.company_101.com',
        '2022-01-01',
        'remark',
        'https://ui-avatars.com/api/?size=300&name=company+101'), ('company_102',
                                                                   'カイシャ',
                                                                   'address',
                                                                   '000-0000',
                                                                   '090102030405',
                                                                   'company_102@gmail.com',
                                                                   'www.company_102.com',
                                                                   '2022-01-01',
                                                                   'remark',
                                                                   'https://ui-avatars.com/api/?size=300&name=company+102'), ('company_103',
                                                                                                                              'カイシャ',
                                                                                                                              'address',
                                                                                                                              '000-0000',
                                                                                                                              '090102030405',
                                                                                                                              'company_103@gmail.com',
                                                                                                                              'www.company_103.com',
                                                                                                                              '2022-01-01',
                                                                                                                              'remark',
                                                                                                                              'https://ui-avatars.com/api/?size=300&name=company+103');


CREATE TABLE account(id SERIAL PRIMARY KEY,
                                       name VARCHAR(255),
                                            name_katakana VARCHAR(255),
                                                          company_name VARCHAR(255),
                                                                       employee_number INT, department VARCHAR(255),
                                                                                                       email VARCHAR(255),
                                                                                                             phone_number VARCHAR(255),
                                                                                                                          address VARCHAR(255),
                                                                                                                                  postal_code VARCHAR(255),
                                                                                                                                              date_of_birth DATE, remark VARCHAR(255),
                                                                                                                                                                         password TEXT, profile_image VARCHAR(255),
                                                                                                                                                                                                      type VARCHAR(255),
                                                                                                                                                                                                           activation VARCHAR(255),
                                                                                                                                                                                                                      active INT, UNIQUE(email),
                                                                                                                                                                                                                                  CONSTRAINT check_type CHECK (type IN ('system admin',
                                                                                                                                                                                                                                                                        'admin',
                                                                                                                                                                                                                                                                        'user')));


INSERT into account(name, name_katakana, company_name, employee_number, department, email, phone_number, address, postal_code, date_of_birth, remark, password, profile_image, type, activation, active)
VALUES ('system_admin',
        'system_admin',
        'company_101',
        '101',
        'department',
        'system_admin@gmail.com',
        '090102030405',
        'address',
        '000-0000',
        '2022-01-01',
        'remark',
        '$2b$10$F7WCXNI9Ik5YSfj13pMEYOSr8BS2ZCcK1ZnyMgvGORCxBb88pKRNu',
        'https://ui-avatars.com/api/?size=300&name=system+admin',
        'system admin',
        '',
        1), ('admin',
             'admin',
             'company_101',
             '102',
             'department',
             'admin@gmail.com',
             '090102030405',
             'address',
             '000-0000',
             '2022-01-01',
             'remark',
             '$2b$10$F7WCXNI9Ik5YSfj13pMEYOSr8BS2ZCcK1ZnyMgvGORCxBb88pKRNu',
             'https://ui-avatars.com/api/?size=300&name=admin',
             'admin',
             '',
             1),('user',
                 'user',
                 'company_101',
                 '103',
                 'department',
                 'user@gmail.com',
                 '090102030405',
                 'address',
                 '000-0000',
                 '2022-01-01',
                 'remark',
                 '$2b$10$F7WCXNI9Ik5YSfj13pMEYOSr8BS2ZCcK1ZnyMgvGORCxBb88pKRNu',
                 'https://ui-avatars.com/api/?size=300&name=system+user',
                 'user',
                 '',
                 1);

